# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TiffinApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ObjectMapper'
  pod 'ReachabilitySwift'
  pod 'IQKeyboardManagerSwift’
  pod 'AMPopTip'
  pod 'RealmSwift'
  pod 'GoogleSignIn'
  pod 'FSCalendar'
  pod 'MGSwipeTableCell'
  pod 'Firebase/Crashlytics'
  # (Recommended) Pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'FittedSheets'
  
  # Pods for TiffinApp

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
